<a href="https://colab.research.google.com/github/Arko2016/Data-Analytics-Projects/blob/main/Retail%20Sales%20Analysis/Retail_Sales_Analysis_nb1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [14]:
url = "https://github.com/Arko2016/Data-Analytics-Projects/raw/main/Retail%20Sales%20Analysis/Regional%20Sales%20Dataset.xlsx"
sheets = pd.ExcelFile(url)
print(sheets.sheet_names)
df = sheets.parse('Sales Orders')
df.head()

['Sales Orders', 'Customers', 'Regions', 'State Regions', 'Products', '2017 Budgets']


OrderNumber  OrderDate  Customer Name Index      Channel Currency Code  \
0   SO - 000225 2014-01-01                  126    Wholesale           USD   
1  SO - 0003378 2014-01-01                   96  Distributor           USD   
2  SO - 0005126 2014-01-01                    8    Wholesale           USD   
3  SO - 0005614 2014-01-01                   42       Export           USD   
4  SO - 0005781 2014-01-01                   73    Wholesale           USD   

  Warehouse Code  Delivery Region Index  Product Description Index  \
0         AXW291                    364                         27   
1         AXW291                    488                         20   
2         AXW291                    155                         26   
3         AXW291                    473                          7   
4         AXW291                    256                          8   

   Order Quantity  Unit Price  Line Total  Total Unit Cost  
0               6      2499.1     14994.6         1824.343  
1              11      2351.7     25868.7         1269.918  
2               6       978.2      5869.2          684.740  
3               7      2338.3     16368.1         1028.852  
4               8      2291.4     18331.2         1260.270

In [17]:
lst = ['apple',5,89,'dog']
lst

['apple', 5, 89, 'dog']

In [21]:
lst.insert(-1,'appy2')
lst

['apple', 5, 89, 'appy1', 'appy', 'appy', 'appy2', 'dog']

In [23]:
lst = ['apple',5,89,'dog']
lst.pop(1)
lst

['apple', 89, 'dog']

In [36]:
lst = [1,4,2,3,1,4,1]
print(lst.index(4))
lstr = lst[::-1] #reverses the list
reverse_index = lstr.index(4)
print(reverse_index)
last_index = len(lst) - reverse_index -1
last_index

1
1


5

In [41]:
original_list = [1, 2, 6, 7, 8]
elements_to_insert = [3, 4, 5]
insert_index = 2
#original_list[insert_index:insert_index] = elements_to_insert
#original_list
original_list.extend(elements_to_insert)
original_list

[1, 2, 6, 7, 8, 3, 4, 5]

In [49]:
lst = [1,2,3]
a = np.prod(lst)
a

np.int64(6)

In [61]:
np1 = np.arange(1,21,step = 1)
np1 = np1.reshape(4,5)
np1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
np1[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [62]:
np1[np1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])